name: Compilar APK DedSec

on:
  push:
    branches: [ "main", "principal" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias para compilar Android
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git libffi-dev libssl-dev python3-dev zip unzip openjdk-17-jdk
          pip install --upgrade pip setuptools
          pip install buildozer cython==0.29.33

      - name: Generar archivo buildozer.spec básico
        run: |
          buildozer init
          sed -i 's/requirements = python3,kivy/requirements = python3,kivy,pillow/' buildozer.spec
          sed -i 's/package.name = myapp/package.name = decsecapp/' buildozer.spec
          sed -i 's/package.domain = org.test/package.domain = org.dedsec/' buildozer.spec

      - name: Compilar APK con Buildozer
        run: |
          yes | buildozer -v android debug

      - name: Subir APK listo para descargar
        uses: actions/upload-artifact@v4
        with:
          name: DedSec-APK-Instalable
          path: bin/*.apk
          
